# Generated by Django 4.1.1 on 2022-10-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import validacao.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256, validators=[validacao.validators.validacao_nome])),
                ('cpf', models.IntegerField(unique=True, validators=[validacao.validators.validacao_cpf])),
                ('data_nascimento', models.DateField(validators=[validacao.validators.validator_data])),
                ('endereco', models.CharField(max_length=256, validators=[validacao.validators.validacao_endereco])),
                ('email', models.CharField(max_length=256, unique=True, validators=[validacao.validators.validacao_email])),
                ('username', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
