# Generated by Django 4.1.1 on 2022-11-07 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usernome',
        ),
    ]
