# Generated by Django 4.1.1 on 2022-11-15 00:22

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_username_usuario_usernome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_nome, validacao.validators.validator_sem_nums]),
        ),
    ]
