# Generated by Django 4.1.1 on 2022-09-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_qualusurio_alter_usuario_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='qualusurio',
            new_name='usuario',
        ),
    ]
