# Generated by Django 4.1.1 on 2022-10-16 15:42

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_rename_qualusurio_usuario_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(unique=True, validators=[validacao.validators.validacao_cpf]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=256, unique=True, validators=[validacao.validators.validacao_email]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_endereco]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_nome]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=20, unique=True, validators=[validacao.validators.validacao_password]),
        ),
    ]
