# Generated by Django 4.1.1 on 2022-10-19 23:51

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_usuario_cpf_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(validators=[validacao.validators.validator_data]),
        ),
    ]
