# Generated by Django 4.1.1 on 2022-11-30 12:56

from django.db import migrations, models
import django.db.models.deletion
import validacao.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField(validators=[validacao.validators.validator_data])),
                ('presente', models.BooleanField()),
                ('nome_aluno_presenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
    ]
