# Generated by Django 4.1.1 on 2022-11-30 12:56

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_aluno', models.CharField(max_length=256, validators=[validacao.validators.validacao_nome, validacao.validators.validator_sem_nums])),
                ('cpf_aluno', models.CharField(max_length=256, unique=True, validators=[validacao.validators.validacao_cpf])),
                ('data_nascimento_aluno', models.DateField(validators=[validacao.validators.validator_data])),
                ('endereco_aluno', models.CharField(max_length=256, validators=[validacao.validators.validacao_endereco])),
                ('turno_aluno', models.CharField(max_length=256)),
                ('arte_marcial_aluno', models.CharField(max_length=256)),
            ],
        ),
    ]
