# Generated by Django 4.1.1 on 2022-10-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0002_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo_aluno', models.CharField(max_length=256)),
                ('cpf_aluno', models.CharField(max_length=256)),
                ('data_nascimento_aluno', models.CharField(max_length=256)),
                ('endereco_aluno', models.CharField(max_length=256)),
                ('turno_aluno', models.CharField(max_length=256)),
                ('arte_marcial_aluno', models.CharField(max_length=256)),
            ],
        ),
    ]
