# Generated by Django 4.1.1 on 2022-10-19 23:40

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_cpf]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento_aluno',
            field=models.DateField(validators=[validacao.validators.validator_data]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='endereco_aluno',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_endereco]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo_aluno',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_nome]),
        ),
    ]
