# Generated by Django 4.1.1 on 2022-10-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_cpf_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento_aluno',
            field=models.DateField(),
        ),
    ]
