# Generated by Django 4.1.1 on 2022-10-28 13:00

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_data_nascimento_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf_aluno',
            field=models.CharField(max_length=256, unique=True, validators=[validacao.validators.validacao_cpf]),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_nascimento_aluno',
            field=models.DateField(validators=[validacao.validators.validator_data]),
        ),
    ]
