# Generated by Django 4.1.1 on 2022-11-15 00:22

from django.db import migrations, models
import validacao.validators


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_alter_aluno_cpf_aluno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo_aluno',
            field=models.CharField(max_length=256, validators=[validacao.validators.validacao_nome, validacao.validators.validator_sem_nums]),
        ),
    ]
